const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Behaviors.bound,
		C3.Behaviors.Platform,
		C3.Behaviors.Sin,
		C3.Behaviors.scrollto,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.ScriptsInEvents.FolhaFase1_Event7_Act2,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.GoToLayout,
		C3.ScriptsInEvents.FolhaFase2_Event7_Act2,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{PlanoDeFundoEmBlocos: 0},
	{PlanoDeFundoFase1: 0},
	{Sólido: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{agua: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Fixar: 0},
	{ZombieM: 0},
	{Teclado: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{cerebro: 0},
	{Áudio: 0},
	{Mouse: 0},
	{Âncora: 0},
	{Coração: 0},
	{VIDAS: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{arvore: 0},
	{arbusto: 0},
	{PlacaSiga: 0},
	{CogumeloRosa: 0},
	{rocha: 0},
	{ArvoreCortada: 0},
	{Sprite18: 0},
	{Caixa: 0},
	{portal: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{RestritoAoLayout: 0},
	{PlanoDeFundoFase2: 0},
	{Sprite20cemiterio: 0},
	{Sprite21cemiterio: 0},
	{Sprite22cemiterio: 0},
	{Sprite24cemiterio: 0},
	{Sprite25cemiterio: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{cavera: 0},
	{Sprite26cemiterio: 0},
	{Sprite27cemiterio: 0},
	{Sprite28cemiterio: 0},
	{Sprite29cemiterio: 0},
	{Sprite30cemiterio: 0},
	{ossos: 0},
	{caveraOsso: 0},
	{Sprite24: 0},
	{placaSigaCemiterio: 0},
	{arvoreMorta: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite28: 0},
	{espinho: 0},
	{Sprite30: 0},
	{Sprite29: 0},
	{Sprite31: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{play: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{fundoVitoriaGameOverHistoria: 0},
	{Texto: 0},
	{Texto2: 0},
	{Texto3: 0},
	{GameOver: 0},
	{yes: 0},
	{no: 0},
	{playAgain: 0},
	{direção: 0},
	{Plataforma: 0},
	{Senóide: 0},
	{caçador: 0},
	{Marcador: 0},
	{RIP: 0},
	{PlanoDeFundoHistoria: 0},
	{PlanoDeHistoria: 0},
	{historia: 0},
	{Texto4: 0},
	{PlanoDeFundogVitoria: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{Texto5: 0},
	{Sprite19: 0},
	{Coração2: 0},
	{CentrarEm: 0},
	{colisão: 0},
	{Vidas: 0},
	{VidasFase2: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoFase1: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	agua: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	ZombieM: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	cerebro: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Coração: class extends self.ISpriteInstance {},
	VIDAS: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	arvore: class extends self.ISpriteInstance {},
	arbusto: class extends self.ISpriteInstance {},
	PlacaSiga: class extends self.ISpriteInstance {},
	CogumeloRosa: class extends self.ISpriteInstance {},
	rocha: class extends self.ISpriteInstance {},
	ArvoreCortada: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Caixa: class extends self.ISpriteInstance {},
	portal: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoFase2: class extends self.ITiledBackgroundInstance {},
	Sprite20cemiterio: class extends self.ISpriteInstance {},
	Sprite21cemiterio: class extends self.ISpriteInstance {},
	Sprite22cemiterio: class extends self.ISpriteInstance {},
	Sprite24cemiterio: class extends self.ISpriteInstance {},
	Sprite25cemiterio: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	cavera: class extends self.ISpriteInstance {},
	Sprite26cemiterio: class extends self.ISpriteInstance {},
	Sprite27cemiterio: class extends self.ISpriteInstance {},
	Sprite28cemiterio: class extends self.ISpriteInstance {},
	Sprite29cemiterio: class extends self.ISpriteInstance {},
	Sprite30cemiterio: class extends self.ISpriteInstance {},
	ossos: class extends self.ISpriteInstance {},
	caveraOsso: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	placaSigaCemiterio: class extends self.ISpriteInstance {},
	arvoreMorta: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	espinho: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	play: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	fundoVitoriaGameOverHistoria: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	GameOver: class extends self.ISpriteInstance {},
	yes: class extends self.ISpriteInstance {},
	no: class extends self.ISpriteInstance {},
	playAgain: class extends self.ISpriteInstance {},
	caçador: class extends self.ISpriteInstance {},
	Marcador: class extends self.ISpriteInstance {},
	RIP: class extends self.ISpriteInstance {},
	PlanoDeFundoHistoria: class extends self.ITiledBackgroundInstance {},
	PlanoDeHistoria: class extends self.ISpriteInstance {},
	historia: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	PlanoDeFundogVitoria: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	Texto5: class extends self.ITextInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Coração2: class extends self.ISpriteInstance {},
	colisão: class extends self.ISpriteInstance {}
}